name: Deploy docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write 
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.27.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist/
      - name: Deploy build page
        id: deployment
        uses: actions/deploy-pages@v1
